version: "3.8"

services:
  server:
    container_name: server
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - MAIN_SERVER_HOST=0.0.0.0
      - MAIN_SERVER_PORT=8080
      - DB_DRIVER=mysql
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=LinkAja

  database:
    container_name: database
    build: ./database/mysql/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin


