package query

const (
	ACCOUNT_INFO = `
	SELECT ACCOUNT_NUMBER, NAME, BALANCE FROM account acc 
	JOIN customer cus ON acc.CUSTOMER_NUMBER = cus.CUSTOMER_NUMBER 
	WHERE ACCOUNT_NUMBER = ?`

	UPDATE_SENDER_BALANCE   = `UPDATE account SET BALANCE = BALANCE - ? WHERE ACCOUNT_NUMBER = ?;`
	UPDATE_RECEIVER_BALANCE = `UPDATE account SET BALANCE = BALANCE + ? WHERE ACCOUNT_NUMBER = ?;`
)
